### ISSUE TITLE
phone number

### ISSUE THREAD

**Issue by 06050890** [Rohitlovewanshi/Hello-Buddy#1]
Can't it be used abroad?   phone check not use abroad phone number?

**Comment by Rohitlovewanshi** [comment]
> Can't it be used abroad? phone check not use abroad phone number?

Yes you can, just change the country code. But ignore the sync buddies menu for now.

**Comment by 06050890** [comment]
where can change country ??   
EX phone number:
+91 XXXXX....);
but me phone number is
+XXX  XXXXXXXX 
where can change code      thank you   
my english is bad sorry

**Comment by Rohitlovewanshi** [comment]
You can change the max length of editText of country code then it will work.

**Comment by Profesorx-1** [comment]
Hello friend, very good code, a question from where do you import this library = com.sinch.android.rtc

**Comment by Rohitlovewanshi** [comment]
Yes, you need to create a account in sinch official website. Then download the aar file from there and paste it under the lib directory and add this line in dependencies : implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])

**Comment by Profesorx-1** [comment]
thanks, another question where do I get this information APP_KEY, APP_SECRET, ENVIRONMENT

**Comment by Profesorx-1** [comment]
API_Key, SESSION_ID, TOKEN ???

**Comment by Rohitlovewanshi** [comment]
Once you have sinch account, add your project there and you will get these things.

**Comment by Profesorx-1** [comment]
Your project is interesting, I already made it work and I added another code so that one can speak to it and write it in the editext. If you want, let me know

**Comment by Rohitlovewanshi** [comment]
yes sure, send me request for your code.

**Comment by Profesorx-1** [comment]
layou activity_message    
<com.airbnb.lottie.LottieAnimationView
            android:id="@+id/send_voice_button"
            android:layout_width="50dp"
            android:layout_height="50dp"
            android:layout_marginStart="1dp"
            android:backgroundTint="@android:color/white"
            app:lottie_autoPlay="true"
            android:scaleType="center"
            app:lottie_fileName="voice6.json"
            app:lottie_imageAssetsFolder="assets"
            app:lottie_loop="true" />
Java MessageActivity 
   
  mBotonVoice=findViewById(R.id.send_voice_button);
  mBotonVoice.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                iniciarEntradaVoice();
            }
        });
    }
    private void iniciarEntradaVoice(){
        Intent intent=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);
        intent.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);
        intent.putExtra(RecognizerIntent.EXTRA_LANGUAGE, Locale.getDefault());
        intent.putExtra(RecognizerIntent.EXTRA_PROMPT,"Hola dime y te lo escribo");
        try {
            startActivityForResult(intent,REQ_CODE_SPEECH_IMPUT);

        }catch (ActivityNotFoundException e){

        }
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        switch (requestCode){
            case REQ_CODE_SPEECH_IMPUT:{
                if (resultCode==RESULT_OK && null!=data){
                    ArrayList<String> result=data.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);
                    text_send.setText(result.get(0));
                }
                break;
            }
        }
    }

**Comment by Profesorx-1** [comment]
I am trying to make him send images or documents if you know something, share it with me, greetings.

**Comment by Rohitlovewanshi** [comment]
ok, Thanks for your code. By the way you can use same approach that we are using for storing profile images of a users.

**Comment by Profesorx-1** [comment]
I have a very advanced code to send images, pdf and doc that should be the next step, in addition to deleting conversations by selection and not by chat

**Comment by Rohitlovewanshi** [comment]
Good bro

**Comment by Rohitlovewanshi** [comment]
I will work on it shortly.

**Comment by Profesorx-1** [comment]
ok

**Comment by 06050890** [comment]
sorry,  sinch need money??    i change "sinchserve"<---- mydata

i can't accept otp    i need change where data???   where can  change country code ?? "Mainactivity"? "loginActivity"
tell me thank you please

**Comment by Rohitlovewanshi** [comment]
check loginActivity.java and activity_login.xml, I updated the code for country code. And please try to understand the code.

**Comment by Profesorx-1** [comment]
hola como va todo? que mejora le pudiste hacer yo te cuento que puede ponerle imagen de cada lado del chat.
![Screenshot_1597597918](https://user-images.githubusercontent.com/65322850/90339901-d2fd9780-dfb9-11ea-9dc1-d5674f0a2f87.png)

**Comment by Rohitlovewanshi** [comment]
I don't know spanish bro.

**Comment by Profesorx-1** [comment]
Hello how is everything? What improvement could you do? I'll tell you that you can put an image on each side of the chat.

**Comment by Profesorx-1** [comment]
what improvement did you make?

**Comment by Rohitlovewanshi** [comment]
> what improvement did you make?

You are doing great bro. I didn't improve anything yet.

**Comment by Profesorx-1** [comment]
Currently it already has images on each side, you can speak and write it in the editext and I am already working on the attachments and it is 100% since in the groupchat the code is almost the same. 
![Screenshot_1597599117](https://user-images.githubusercontent.com/65322850/90340265-8b2c3f80-dfbc-11ea-8cdc-a17c104574c5.png)

**Comment by Rohitlovewanshi** [comment]
Nice bro

**Comment by 06050890** [comment]
thank  ， I solved the problem，but i have question,sinch need money to use???
